### ISSUE TITLE
3D Pose from vertices

### ISSUE THREAD

**Issue by boza-wd** [microsoft/MeshTransformer#14]
Hi!

Once again, kudos for the amazing work, I can't wait for the Mesh Graphormer to get out (hopefully it will). 

Is there a part of the code where we can extract 3D Pose (and also maybe betas) from vertices, similarly like you did for 3D Joints (get_joints)?

Cheers!

**Comment by kevinlin311tw** [comment]
Thanks a lot for your interests in our work! 

Yes. We are planning to release Mesh Graphormer, probably just add it in this repo.

Unfortunately we don't have code to recover 3D Pose (i.e., theta of SMPL). There are two ways to recover it:
1. Add a MLP on top of the output mesh to predict theta and beta, similar to Fig3 in https://arxiv.org/pdf/1905.03244.pdf
2. Use Equation 1 in https://dl.acm.org/doi/abs/10.1145/2816795.2818013 to find theta.

**Comment by boza-wd** [comment]
Thanks for the proposed ideas. I added MLP on top and it works good enough! Cheers! 

ps. Looking forward to Mesh Graphormer!

**Comment by kevinlin311tw** [comment]
Great to know it works!

Thanks for your interest in our work. We are now refactoring mesh-graphormer codebase. We will release it soon.

**Comment by xiaoyang333** [comment]
> 


请问你能介绍你的mlp在哪里连接的上，输入是什么呢，是mano网格顶点坐标还是文章中的特征向量
Can you tell me where your mlp is connected, and what the input is? Is it the vertex coordinates of the mano grid or the eigenvector in the article
