### ISSUE TITLE
3D mesh is not generated

### ISSUE THREAD

**Issue by tqtrunghnvn** [microsoft/MeshTransformer#15]
Hi,

First of all, thank you so much for your contribution!

I am facing a problem when running your quick demo code. I hope 3D mesh is generated as shown in your demo.
![image](https://user-images.githubusercontent.com/25926452/124237363-a60a9280-db41-11eb-8093-baefce2ec7a5.png)

However, 3D mesh was not generated in my example.

Could you please give me some advice?

**Comment by kevinlin311tw** [comment]
Could you send your test sample to me? I can try running it.

**Comment by tqtrunghnvn** [comment]
I simply downloaded an image from the internet. You can try with this following one:
https://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/64/2018/12/champ-630x473.jpg

**Comment by kevinlin311tw** [comment]
Two more questions:
1. Are you able to generate our 3D mesh examples? This is to make sure you have install the code correctly.
2. Before feeding your golf image, do you crop the image with a size of 224x224? We need 224x224 image size.
3. Could you please share any error messages you got here?

**Comment by tqtrunghnvn** [comment]
Hi,
I was not able to generate the 3D mesh for your examples.
I got:
![3dpw_test1_metro_pred](https://user-images.githubusercontent.com/25926452/124409406-6d053480-dd72-11eb-8d97-6f27c3647a0f.jpg)
![3dpw_test2_metro_pred](https://user-images.githubusercontent.com/25926452/124409412-70002500-dd72-11eb-8f78-2f1aaa455231.jpg)
![3dpw_test3_metro_pred](https://user-images.githubusercontent.com/25926452/124409419-71c9e880-dd72-11eb-98c1-ba43b2da298c.jpg)

Could you please try to run another sample?

**Comment by kevinlin311tw** [comment]
You may find it here.

![champ_metro_pred](https://user-images.githubusercontent.com/9973040/124670405-ccde0700-de68-11eb-95b1-ed7d22241f60.jpg)

In your attached results, I see you have generated the attention visualization with the output vertices. This indicates 3D mesh is generated. The issue you got is probably a rendering issue. I would suggest to double check the installation, making sure OpenDR is successfully installed.

**Comment by tqtrunghnvn** [comment]
Hmm. Thank you for your effort!

I have double-checked opendr installation, and is successfully installed and could be imported without any problems.
Could you tell me where is the **code** for generating **3D mesh** (NOT attention visualization)?

**Comment by kevinlin311tw** [comment]
I guess you are referring to rendering 3D mesh, right? You may check it here: https://github.com/microsoft/MeshTransformer/blob/44760db076e4dd1220c907b2b01a8b0e8c3a334c/metro/utils/renderer.py#L405

Basically it takes mesh vertices, camera parameters, input image as inputs. It will render 3D pink mesh on top of the image.

**Comment by tqtrunghnvn** [comment]
Is it mandatory to install the dependencies with the following versions?
- Python 3.7
- Pytorch 1.4
- torchvision 0.5.0
- cuda 10.1

**Comment by kevinlin311tw** [comment]
We verified that our code works with the dependencies. I would suggest to literally follow our installation instruction, and make sure you can reproduce our demo examples.

**Comment by tqtrunghnvn** [comment]
Thank you so much! The problem is solved.

**Comment by zws2lll** [comment]
@tqtrunghnvn hi, tqtrunghnvn, could you tell me how to solve this problem? I run the demo on gpu 3090.

**Comment by tqtrunghnvn** [comment]
Hi @zws2lll , you should check your opendr installation.

**Comment by zws2lll** [comment]
@tqtrunghnvn I use "pip install opendr", and it's 0.78. There's no error. How do you check the opendr?


Successfully built opendr
Installing collected packages: opendr
  Attempting uninstall: opendr
    Found existing installation: opendr 0.76
    Uninstalling opendr-0.76:
      Successfully uninstalled opendr-0.76
Successfully installed opendr-0.78

**Comment by tqtrunghnvn** [comment]
You could try:
https://gitlab.eecs.umich.edu/ngv-python-modules/opendr

**Comment by zws2lll** [comment]
I clone it and "pip install .". 0.76 is installed. The output contains no render hand

**./metro/tools/end2end_inference_handmesh.py --resume_checkpoint ./models/metro_release/metro_hand_state_dict.bin --image_file_or_path ./samples/hand/**
![freihand_sample3_metro_pred](https://user-images.githubusercontent.com/12002211/140033451-de2a2fc4-bbe8-42db-907f-5184c2df25f3.jpg)

**Comment by zws2lll** [comment]
> I clone it and "pip install .". 0.76 is installed. The output contains no render hand
> 
> **./metro/tools/end2end_inference_handmesh.py --resume_checkpoint ./models/metro_release/metro_hand_state_dict.bin --image_file_or_path ./samples/hand/** ![freihand_sample3_metro_pred](https://user-images.githubusercontent.com/12002211/140033451-de2a2fc4-bbe8-42db-907f-5184c2df25f3.jpg)

@kevinlin311tw hi, kevinlin311tw. I also use your docker image. Same result with no render hand. Any Suggestion？

**Comment by tqtrunghnvn** [comment]
@zws2lll I also used opendr0.76. Sorry I have no idea now

**Comment by zws2lll** [comment]
Thank you anyway.

**Comment by fmx789** [comment]
> Thank you anyway.

@zws2lll Hi, have you solved the problem? Such a circumstance perplexes me as well.

**Comment by JCheng314** [comment]
For hand, I pulled relevant codes for generating mesh on the images and stored the vertices, camera data, then did the mesh generation in a separate file, and mesh is generated, but I don't know why the almost exactly the same code doesn't work.
