### ISSUE TITLE
colab

### ISSUE THREAD

**Issue by AK391** [microsoft/MeshTransformer#18]
can you please add a colab for inference?

**Comment by kevinlin311tw** [comment]
Thanks for the suggestions. I will look into this...

**Comment by boza-wd** [comment]
This can serve as an idea...
https://colab.research.google.com/drive/1VCevFPN68w0orcYLu4E8iaHJshQlTM73?usp=sharing

**Comment by kevinlin311tw** [comment]
Thank you @boza-wd for the awesome colab code! 
please feel free to submit a pull request, and I will add your colab to the repo.
