### ISSUE TITLE
About 3DPW dataset

### ISSUE THREAD

**Issue by thancaocuong** [microsoft/MeshTransformer#19]
thank for your interesting works. I have a concern about how did you generate the .tsv file for 3DPW dataset? I mean from original dataset. thanks

**Comment by kevinlin311tw** [comment]
Thanks for the question!

Regarding 3DPW, we directly use the pre-parsed annotations provided by [Pose2Mesh](https://github.com/hongsukchoi/Pose2Mesh_RELEASE). We found it is well-maintained in COCO format, so we just reorganize their annotations to fit our tsv format. 

You may find our example code of preparing TSV files [here](https://github.com/microsoft/MeshTransformer/blob/main/metro/tools/tsv_demo.py). In the example, it will build the TSV files for UP-3D dataset from scratch. It will need some trivial modifications to adapt to other datasets, but this should give you a general picture about how we build TSV files.

**Comment by thancaocuong** [comment]
@kevinlin311tw  thank you for your help. I read your code and understand that you will crop image by bounding box provided by 2d joints. So if I want to run on whole 3DPW dataset images, should I use object detector like yolov5 to first extract the human bounding boxes, then take prediction?

**Comment by kevinlin311tw** [comment]
Yes. You are right!

**Comment by thancaocuong** [comment]
thank you so much
