### ISSUE TITLE
Can't download datasets

### ISSUE THREAD

**Issue by KailinLi** [microsoft/MeshTransformer#2]
Hi! Thank you for releasing the code! 

When I tried to download datasets with **AzCopy**, I got this error:

```
./azcopy copy 'https://datarelease.blob.core.windows.net/metro/datasets/datasets_release/freihand' ~/Downloads --recursive  
INFO: Scanning...

failed to perform copy command due to error: Login Credentials missing. No SAS token or OAuth token is present and the resource is not public
```

I guess the datasets are not publicly available yet?

All the best,

Kailin

**Comment by kevinlin311tw** [comment]
Thanks for pointing out it. Let me check the permission issues.

**Comment by kevinlin311tw** [comment]
The download instruction has been updated.

To download the files, please use the following command.
```
cd $REPO_DIR
path/to/azcopy copy 'https://datarelease.blob.core.windows.net/metro/datasets/filename.tar' /path/to/your/folder/filename.tar
tar xvf filename.tar  
```
`filename.tar` could be `Tax-H36m-coco40k-Muco-UP-Mpii.tar`, `human3.6m.tar`, `coco_smpl.tar`, `muco.tar`, `up3d.tar`, `mpii.tar`, `3dpw.tar`, `freihand.tar`. Please check our document for further details about the directory structure.

**Comment by KailinLi** [comment]
Successfully downloaded the datasets. Thanks for your reply!
