### ISSUE TITLE
Mapping 3D pose from cropped image patch to the original images!

### ISSUE THREAD

**Issue by thancaocuong** [microsoft/MeshTransformer#20]
To deal with multi-person 3d pose estimation, I've run the METRO to get 3d joints from smpl (use get_joints function) on the cropped patches of image. So now I have the joints with shape 1x24x3 for each patch. For a given cropped bounding box like [x, y, w, h]. How can I reverse to the original image 3d joints? Thanks

**Comment by kevinlin311tw** [comment]
Could you elaborate a bit more about your question? What is "**reverse to the original image 3d joints**"?

**Comment by tqtrunghnvn** [comment]
The same question. I think he means how to plot the keypoints onto the image.

I found that the 3D joints contain negative numbers, so how could we transform the predicted 3D joints to 2D joints so that we can draw them onto the image?

**Comment by thancaocuong** [comment]
@kevinlin311tw look at [this line](https://github.com/microsoft/MeshTransformer/blob/44760db076e4dd1220c907b2b01a8b0e8c3a334c/metro/tools/end2end_inference_bodymesh.py#L80). the 3d result here is the final result of 3d Pose (for 14 joints). But these are the coordinates at 224x224 scale. So my question **"reverse to the original image 3d joints"?** is that suppose I crop from  the image of size (original_W, original_H)  with bounding box [x, y, w, h] then I get the image patch of size 224x224. I feed it into metro to retrieve the 14 joints 3d coordinates. So how can I convert the result back to the (original_W, original_H) image.

**Comment by kevinlin311tw** [comment]
Thanks for the clarification! To render the 3D results in the original image coordinate, you will need to convert some coordinate systems. 

I will add new code to do it. At the same time, if you are in a hurry, you may also like to check [HMR](https://github.com/akanazawa/hmr) for quick solutions as we use a very similar (almost the same) rendering tool.
