### ISSUE TITLE
Doubts about results

### ISSUE THREAD

**Issue by Shubhendu-Jena** [microsoft/MeshTransformer#21]
Hi,

Thank you for the great work! In the results section of your paper, you've stated results for your training on many datasets for 200 epochs. I was wondering if you also happen to have trained your model only on Human3.6M or Human3.6M+COCO. If you do, I'd be grateful if you could let me know.

Thanks in advance

**Comment by kevinlin311tw** [comment]
Thanks for the great question!

At that time, we think Transformer usually requires large amount of training data to learn well, so we didn't put much efforts in exploring the small-data training regime. 

As I remember, we tried that once, but the results were not good. unfortunately I don't have the numbers now :(

**Comment by Shubhendu-Jena** [comment]
Thanks for the response. Indeed, it makes more for transformers to use a large amount of training data. Cheers again for the nice work!
