### ISSUE TITLE
error in end2end_inference_bodymesh.py

### ISSUE THREAD

**Issue by ccq195** [microsoft/MeshTransformer#24]
Hi, how to solve the error when i run end2end_inference_bodymesh.py?

config.output_attentions = False
AttributeError: 'NoneType' object has no attribute 'output_attentions'

**Comment by kevinlin311tw** [comment]
Could you please share your command and the entire output log here?

**Comment by ClimberY** [comment]
Excuse me, have you solved this problem?

**Comment by qqq1357962** [comment]
I met the same problem

**Comment by qqq1357962** [comment]
![image](https://user-images.githubusercontent.com/58675927/157568955-b2209325-813c-4c46-b03a-a941cb10f70c.png)

**Comment by kevinlin311tw** [comment]
It is a known issue if you don't successfully load checkpoints and configs, and therefore it cannot recognize config.output_attentions. 

Possible reason could be incorrect folder path. Please have a check if you load them correctly. Thank you.
