### ISSUE TITLE
questions on 3DPW

### ISSUE THREAD

**Issue by siyuzou** [microsoft/MeshTransformer#27]
Hi! Thanks for your great work.
I have some questions about training on 3DPW.

1. According to [docs/EXP.md](https://github.com/microsoft/MeshTransformer/blob/main/docs/EXP.md), when train on 3DPW, `3dpw/test_has_gender.yaml` is used to evaluate during training:
    ```bash
    --val_yaml 3dpw/test_has_gender.yaml \
    ```
    When evaluate on 3DPW after training, `3dpw/test.yaml` is used instead:
    ```bash
    --val_yaml 3dpw/test.yaml \
    ```
    I only find `test_has_gender.yaml` in the provided `3dpw.tar` archive. Are the above 2 files the same? If not, what are the differences?

2. According to [metro/tools/tsv_demo_3dpw.py#L71](https://github.com/microsoft/MeshTransformer/blob/main/metro/tools/tsv_demo_3dpw.py#L71) and [metro/tools/run_metro_bodymesh.py#L395](https://github.com/microsoft/MeshTransformer/blob/main/metro/tools/run_metro_bodymesh.py#L395), neutral SMPL model is used to generate GT kp3d and GT vertices, for both 3DPW train set and testing set. I wonder if it is correct because 3DPW provides `gender` attributes, and only use the model corresponding to the given gender gives the correct output, as far as I know. 

Thanks again and looking forward to your reply!

**Comment by kevinlin311tw** [comment]
Thanks a lot for the suggestions. This would be a reasonable solution. We will definitely try to add gender information for both training and testing.
