### ISSUE TITLE
Poor results using end2end_inference_bodymesh

### ISSUE THREAD

**Issue by Gowan1998** [microsoft/MeshTransformer#31]
Hello, 
thank you very much for this great project. I have done many tests (inference only). The results are very bad and I want to ask you if I am doing something wrong? I did exactly what is suggested in DEMO.md. Should I do something additional? 
Here some poor results:
![Screenshot from 2021-08-30 11-43-16](https://user-images.githubusercontent.com/22528147/131320611-5c4dc357-3ed5-4a1b-b939-9b11decf2e4d.png)

![3dpw_sit_on_street_metro_pred](https://user-images.githubusercontent.com/22528147/131320562-3fa7f47a-ce97-4524-8a61-492e2f9b4647.jpg)

**Comment by kevinlin311tw** [comment]
Our model will not work well if the target is not at the center of the input image. It is very sensitive to shifting.

**Comment by kevinlin311tw** [comment]
In this research topic, people generally normalize the reconstruction target at the center of the input image using bounding box (either from GT, object detector, or pose estimation). It is used for both training and testing.

If your testing images are not normalized as we did in training, our model may not work well.

**Comment by ShawanMohammed1989** [comment]
Hello kevin,
thank you very much for your answer. I thought that detection is already implemented. 
That means I have to use a detector (e.g. Yolo) before I use the inference script.
