### ISSUE TITLE
No such file of ''metro/tools/run_hand_inference.py''

### ISSUE THREAD

**Issue by Vegetebird** [microsoft/MeshTransformer#36]
As you metioned in EXP.md. 

python metro/tools/run_hand_inference.py \
       --model_path models/metro_released/metro_hand_state_dict.bin \

But there is no this file.

**Comment by kevinlin311tw** [comment]
Sorry for the typos. Please try `end2end_inference_handmesh.py`, but not `run_hand_inference.py`
