### ISSUE TITLE
"joints_2d" data is wrong in human3.6m/valid.protocol2.yaml.

### ISSUE THREAD

**Issue by wkailiu** [microsoft/MeshTransformer#37]
![2021-09-15_15-12](https://user-images.githubusercontent.com/44597208/133387759-ed07f287-5a47-430f-b1e2-70ce0b74f048.png)

**Comment by kevinlin311tw** [comment]
The 2d joints in the validation tsv are just placeholder. We only evaluate 3D pose. We don't use 2d joint labels in our evaluation.
