### ISSUE TITLE
The max sequence length

### ISSUE THREAD

**Issue by zhiwenfan** [microsoft/MeshTransformer#39]
Hi, thank you for open source your nice work.
I was wondering about the number of supported sequence lengths.
Because when I use the sequence length larger than 512, it throws the following error(the code is ok with a smaller sequence length with default setting):
********

/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [64,0,0], thread: [19,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [64,0,0], thread: [20,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [64,0,0], thread: [21,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [64,0,0], thread: [22,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [64,0,0], thread: [23,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [64,0,0], thread: [24,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [64,0,0], thread: [25,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [64,0,0], thread: [26,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [64,0,0], thread: [27,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [64,0,0], thread: [28,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [64,0,0], thread: [29,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [64,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/tmp/pip-req-build-g2m34a_4/aten/src/ATen/native/cuda/Indexing.cu:690: indexSelectLargeIndex: block: [64,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

RuntimeError: CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below
might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. CUDA error: device-side assert triggered

**Comment by kevinlin311tw** [comment]
By default, the max length is 512. You need to update the parameter `max_position_embeddings` in bert config accordingly.

Check out huggingface's code
https://github.com/huggingface/transformers/blob/067923d3267325f525f4e46f357360c191ba562e/pytorch_transformers/modeling_bert.py#L172
