### ISSUE TITLE
Mano trans parameter for mano layer

### ISSUE THREAD

**Issue by Bozcomlekci** [microsoft/MeshTransformer#42]
Greetings,

I couldn't understand why trans parameter is not passed to the mano layer for extracting `gt_3d_joints` and `gt_vertices`. Some of the implementations (I2L-MeshNet) were using `mano_trans` and I'm confused about its function.

Besides, I'm confused about subtracting the root wrist from `gt_vertices` and 'gt_3d_joints'. Why do you perform this operation in both training and inference? 

Thanks in advance.

**Comment by kevinlin311tw** [comment]
In our code, we didn't consider the translation, and we normalize the root during training/testing.
