### ISSUE TITLE
Issue downloading the data

### ISSUE THREAD

**Issue by mkhoshle** [microsoft/MeshTransformer#43]
Hello, 

When I try to download the data from 'https://datarelease.blob.core.windows.net/metro/datasets/filename.tar' using the following command:
```
%%bash
# copy Snapshot Serengeti images to a local directory
DATASET_URL="https://datarelease.blob.core.windows.net/metro/datasets/filename.tar"
LOCAL_DIR="/content/MeshTransformer"

./azcopy cp "${DATASET_URL}" "${LOCAL_DIR}" 

```
I get this error:
```
INFO: Scanning...

failed to perform copy command due to error: Login Credentials missing. No SAS token or OAuth token is present and the resource is not public
```
Is it possible to download the data?

**Comment by mkhoshle** [comment]
I resolved this issue as I had a mistake. I had to put the name of the dataset instead of filename. e.g. freihand.

**Comment by wang-zm18** [comment]
> I resolved this issue as I had a mistake. I had to put the name of the dataset instead of filename. e.g. freihand.

hello, I found the link is invalid... Could you please share these datasets with me? Thank you in advance!
