### ISSUE TITLE
how to fine-tone your pre-train model using my data

### ISSUE THREAD

**Issue by 2017211801** [microsoft/MeshTransformer#44]
Hello,

Thank you for your wonderful work. It's really impressive.

let's cut to the chase,  how to fine-tone your pre-train model using my data. Specifically, how to reorganize my data format (.png) to the following:

|   |-- up3d  
|   |   |-- trainval.img.tsv  
|   |   |-- trainval.hw.tsv   
|   |   |-- trainval.label.tsv
|   |   |-- trainval.linelist.tsv

I would appreciate any and all help you can give!

Thanks.

**Comment by kevinlin311tw** [comment]
You can organize your data in any way you feel comfortable. The most important thing is to make sure you follow our example code to generate tsv files. You can find the example code here: [https://github.com/microsoft/MeshTransformer/blob/main/metro/tools/tsv_demo_up3d.py](https://github.com/microsoft/MeshTransformer/blob/main/metro/tools/tsv_demo_up3d.py)
