### ISSUE TITLE
Question about the use of Smpl and MANO in METRO

### ISSUE THREAD

**Issue by mkhoshle** [microsoft/MeshTransformer#46]
I have confusion regarding the use of SMPL and MANO in your model. In your paper, you mention that the image feature is concatenated with the 3D coordinates of everybody joint i, and 3D coordinates of every vertex j. Based on the code my understanding is that SMPL and MANO are used for this purpose. But these are themselves parametric models which provide body shape and pose. So why are you concatenating the body mesh and joint vertices obtained from SMPL and MANO to create the body mesh again?

I would really appreciate it if you could further clarify this.

**Comment by kevinlin311tw** [comment]
We use SMPL/MANO only for generating a template mesh. 

In a high-level perspective, our transformer model is learning to deform the template mesh with a desired pose and shape.
