### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by ClimberY** [microsoft/MeshTransformer#49]
MeshTransformer-main/metro/tools/end2end_inference_bodymesh.py --resume_checkpoint ./models/metro_release/metro_3dpw_state_dict.bin --image_file_or_path ./samples/human-body
2021-12-22 20:25:42,376 METRO Inference INFO: Using 1 GPUs
anaconda3/envs/metro/lib/python3.7/site-packages/scipy/sparse/_index.py:84: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])
anaconda3/envs/metro/lib/python3.7/site-packages/scipy/sparse/_index.py:84: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])
anaconda3/envs/metro/lib/python3.7/site-packages/scipy/sparse/_index.py:84: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])
Model name 'metro/modeling/bert/bert-base-uncased/' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc). We assumed 'metro/modeling/bert/bert-base-uncased/' was a path or url but couldn't find any file associated to this path or url.
Traceback (most recent call last):
  File "MeshTransformer-main/metro/tools/end2end_inference_bodymesh.py", line 316, in <module>
    main(args)
  File "MeshTransformer-main/metro/tools/end2end_inference_bodymesh.py", line 222, in main
    config.output_attentions = False
AttributeError: 'NoneType' object has no attribute 'output_attentions'
2021-12-22 20:25:47,352 METRO Inference INFO: Inference: Loading from checkpoint ./models/metro_release/metro_3dpw_state_dict.bin

**Comment by kevinlin311tw** [comment]
Did you run the commands under the main folder?

**Comment by kevinlin311tw** [comment]
Can you please check if you successfully load the checkpoint?

**Comment by kevinlin311tw** [comment]
This is a known issue when it doesn't successfully load the checkpoint and config files. As a result, it cannot recognize `config.output_attentions`. 

Please double check if you correctly load the checkpoints and config files during initialization. Please re-open this thread if you encounter relevant issues again. Thank you.
