### ISSUE TITLE
can you provide the exactly name of the 14 joints that you estimated,Thanks~

### ISSUE THREAD

**Issue by visonpon** [microsoft/MeshTransformer#5]
Hi, thanks for your great work,  and I notice that the code  can get `pred_3d_joints `and `pred_3d_joints_from_smpl`, when I print their shape, I got 14 and 17 respectively, but since smpl have 24 joints,  hope you can tell which joints are contained in those predicted joints, 
And I also hope if you can give some advice on how to obtain the root motion based on the predicted, thanks~

**Comment by kevinlin311tw** [comment]
Hope this info would help. 

https://github.com/microsoft/MeshTransformer/blob/6d5747a928b46b7e2e20d06008e489b8e52b4742/metro/modeling/data/config.py#L32-L37

**Comment by visonpon** [comment]
got it ,thanks~

**Comment by kevinlin311tw** [comment]
Unfortunately our code doesn't have this function. I am not sure how to do that.
