### ISSUE TITLE
ileNotFoundError: [Errno 2] No such file or directory: 'models/hrnet/cls_hrnet_w64_sgd_lr5e-2_wd1e-4_bs32_x100.yaml'

### ISSUE THREAD

**Issue by Ngheissari** [microsoft/MeshTransformer#53]
Hi,

It is asking for 
ileNotFoundError: [Errno 2] No such file or directory: 'models/hrnet/cls_hrnet_w64_sgd_lr5e-2_wd1e-4_bs32_x100.yaml'
when running 
 python ./metro/tools/end2end_inference_bodymesh.py  --resume_checkpoint ./models/metro_release/metro_3dpw_state_dict.bin --image_file_or_path ./samples/human-body

There is no models/hrnet/ folder . Where should it be ?

**Comment by jayyoung0802** [comment]
Hi @Ngheissari, can you share the metro_hand_state_dict.bin? It cannot be downloaded from the download script. My email is jayyoung0802@gmail.com
