### ISSUE TITLE
What's speed of Hand MeshTransformer compared with other methods such as CNN？

### ISSUE THREAD

**Issue by youngstu** [microsoft/MeshTransformer#6]
What's speed of Hand MeshTransformer compared with other methods such as CNN？

**Comment by kevinlin311tw** [comment]
It is roughly 12 fps based on a single NVIDIA P100 GPU. I think the speed could be further improved with better implementation but we didn't put much engineering effort into it.
For the speed related experiments, you may want to check the appendix of our arxiv paper. Thanks.

**Comment by youngstu** [comment]
Thanks. There may be some room for optimization to run on mobile phones in real time.
