### ISSUE TITLE
Download datasets error

### ISSUE THREAD

**Issue by PomIsBest** [microsoft/MeshTransformer#61]
When I want to download datasets from azcopy,I get an error of 'Login Credentials missing.No SAS token or OAuth token is present and the resource is not public'.I would very much appreciate it if you could give me some help to solve this problem.

Thanks for your great work!

**Comment by kevinlin311tw** [comment]
If you were using the example script, please remember to change `filename` to the one you would like to download. If you just run the example script, it will not work. For example, if you are trying to download `up3d.tar`, then you should literately change `filename.tar` to `up3d.tar`

Specifically, after changing the script, it should look like this:
```
cd $REPO_DIR
path/to/azcopy copy 'https://datarelease.blob.core.windows.net/metro/datasets/up3d.tar' /path/to/your/folder/up3d.tar
tar xvf up3d.tar
```

**Comment by PomIsBest** [comment]
I got it! 
I misunderstood the meaning before, now I can download the datasets successfully!
Thank you very much for your answer!
