### ISSUE TITLE
Code to reproduce Freihand tsv files

### ISSUE THREAD

**Issue by EAST-J** [microsoft/MeshTransformer#64]
Hi, thx for your nice work. There are codes to reproduce human3.6M, 3DPW tsv files, I wonder can you share the code to reproduce Freihand tsv files?

**Comment by kevinlin311tw** [comment]
Thanks for the questions. I will upload it when it is ready.

**Comment by kevinlin311tw** [comment]
The example code is added. You may find it here: [metro/tools/tsv_demo_freihand.py](https://github.com/microsoft/MeshTransformer/commit/f8025d3c34d61d72dd9795385fa66f065be4aebc#diff-2be3e59b1e47d4625d322c1108cfb88e7d3395b6112991dac148be0dda0d838e)
