### ISSUE TITLE
Sub-sampling generic mesh

### ISSUE THREAD

**Issue by zc-alexfan** [microsoft/MeshTransformer#65]
Hi, thanks for sharing your code. I noticed that a mano sub-sampler is loading a npz file which provides the downsampling matrices for MANO. I am wondering if you could provide some pointers to allow downsampling and upsampling of generic meshes (you can assume watertight or not). Thanks.

**Comment by kevinlin311tw** [comment]
Thanks for the question! The downsampling and upsampling matrix are computed by using a sampling algorithm proposed in this ECCV2018 paper: [COMA: Generating 3D Faces using Convolutional Mesh Autoencoders](https://coma.is.tue.mpg.de/)

You could take a look their code, especially this function:  https://github.com/anuragranj/coma/blob/master/main.py#L47

**Comment by zc-alexfan** [comment]
Thanks a lot!
