### ISSUE TITLE
Datasets download failed using azcopy copy command

### ISSUE THREAD

**Issue by youngstu** [microsoft/MeshTransformer#7]
failed to perform copy command due to error: Login Credentials missing. No SAS token or OAuth token is present and the resource is not publi

**Comment by kevinlin311tw** [comment]
Please provide more information and the commands you used, so that we can better identify the issue.

Please also check #2 in case you are following the old document.

**Comment by bozo-wd** [comment]
I also had an issue with one particular download - muco.tar, for some reason azcopy gives an output that it failed downloading it. But then you can just use the browser, just type https://datarelease.blob.core.windows.net/metro/datasets/muco.tar, or (my recommendation) by using xdm download manager (if you are on the linux based OS). it is faster than azcopy, but on the other hand it requires a bit of manual labour (copy/paste).
PS. You can download every single file (Tax-H36m-coco40k-Muco-UP-Mpii.tar, human3.6m.tar, ...) in this manner, in case you keep having the issue with azcopy.
