### ISSUE TITLE
pre-trained models！ERROR 400: Bad Request.

### ISSUE THREAD

**Issue by Bodhi007** [microsoft/MeshTransformer#79]
I followed the steps to arrive：
Download pretrained models.
The original script file could not be executed, so I changed it as follows:
###
export REPO_DIR=$PWD
BLOB='https://datarelease.blob.core.windows.net/metro'
wget -nc $BLOB/models/metro_h36m_state_dict.bin -O ./models/metro_release/metro_h36m_state_dict.bin
wget -nc $BLOB/models/metro_3dpw_state_dict.bin -O ./models/metro_release/metro_3dpw_state_dict.bin
wget -nc $BLOB/models/metro_hand_state_dict.bin -O ./models/metro_release/metro_hand_state_dict.bin

###

But the error is still reported：

(metro1) [20lzw@dc1 MeshTransformer]$ bash scripts/download_models.sh
--2023-01-15 00:23:55--  https://datarelease.blob.core.windows.net/metro%0D/models/metro_h36m_state_dict.bin
Resolving datarelease.blob.core.windows.net (datarelease.blob.core.windows.net)... 20.150.35.196
Connecting to datarelease.blob.core.windows.net (datarelease.blob.core.windows.net)|20.150.35.196|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2023-01-15 00:23:56 ERROR 400: Bad Request.

--2023-01-15 00:23:56--  https://datarelease.blob.core.windows.net/metro%0D/models/metro_3dpw_state_dict.bin
Resolving datarelease.blob.core.windows.net (datarelease.blob.core.windows.net)... 20.150.35.196
Connecting to datarelease.blob.core.windows.net (datarelease.blob.core.windows.net)|20.150.35.196|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2023-01-15 00:23:57 ERROR 400: Bad Request.

--2023-01-15 00:23:57--  https://datarelease.blob.core.windows.net/metro%0D/models/metro_hand_state_dict.bin
Resolving datarelease.blob.core.windows.net (datarelease.blob.core.windows.net)... 20.150.35.196
Connecting to datarelease.blob.core.windows.net (datarelease.blob.core.windows.net)|20.150.35.196|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
2023-01-15 00:23:58 ERROR 400: Bad Request.

**Comment by 1a2a3x** [comment]
Hello, may I ask if you have obtained the pre-trained models? Could you please send them to my email at [3136706035@qq.com](https://mailto:3136706035@qq.com/)?
